version: "3.7"

services:

  eh:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: eh
    restart: always
    ports:
      - 8018:80
#      - 443:443
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000
    networks:
      - eh
    volumes:
      - ./:/var/www/html
      - ./log:/var/log/nginx
      - ./docker/config/php.ini:/usr/local/etc/php/php.ini # mapping php.ini
      - ./docker/config/supervisord.conf:/etc/supervisor/supervisord.conf # mapping supervisord.conf
      - ./docker/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini # disable xdebug for high performance
      - ./docker/config/nginx.conf:/etc/nginx/nginx.conf #mapping nginx.conf
networks:
  eh:
    driver: bridge
